# Generated by Django 6.0 on 2025-12-19 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_chatsession_chatmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatsession',
            old_name='title',
            new_name='titulo',
        ),
    ]
