# Generated by Django 6.0 on 2025-12-19 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_title_chatsession_titulo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='menssagem',
            new_name='mensagem',
        ),
        migrations.RenameField(
            model_name='chatsession',
            old_name='created_at',
            new_name='criado_em',
        ),
    ]
