# Generated by Django 6.0 on 2025-12-20 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_chatmessage_user_alter_chatsession_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='distrito',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='provincia',
        ),
    ]
