# Generated by Django 6.0 on 2025-12-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_chatmessage_distrito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pode_vender',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='tipos',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('AGRICULTOR', 'Agricultor')], default='AGRICULTOR', max_length=20),
        ),
    ]
