# Generated by Django 6.0 on 2025-12-28 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_pode_vender_user_tipos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('votos_aprovacao', models.PositiveIntegerField(default=0)),
                ('votos_rejeicao', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('VALIDADA', 'Validada'), ('DESCARTADA', 'Descartada')], default='PENDENTE', max_length=20)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('criada_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tecnicas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VotoTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voto', models.CharField(choices=[('APROVA', 'Aprova'), ('REPROVA', 'Reprova')], max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('tecnica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tecnica')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'tecnica')},
            },
        ),
    ]
