# Generated by Django 6.0 on 2026-03-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitymessage',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='comunidade/'),
        ),
    ]
