# Generated by Django 6.0 on 2026-03-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_produto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='foto',
            field=models.ImageField(default='produtos/placeholder.jpg', upload_to='produtos/'),
        ),
    ]
