"""
Django settings for iagromoz project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from corsheaders.defaults import default_headers
from dotenv import load_dotenv
import os
import sys
from decouple import config

# Load environment variables from .env file
load_dotenv()


GOOGLE_API_KEY = os.getenv('GOOGLE_API_KEY')
GOOGLE_CLIENT_ID = config('GOOGLE_CLIENT_ID', default='')




AUDIT_ENABLED = os.getenv("AUDIT_ENABLED", "true").lower() == "true"
if len(sys.argv) > 1 and sys.argv[1] in ["migrate", "makemigrations"]:
    AUDIT_ENABLED = False

# ---------------------------------------------------------------------------
# Cache — usar memória local em dev, Redis em prod
# ---------------------------------------------------------------------------
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'iagromoz-cache',
    }
}

# Bloqueio de conta após N tentativas de login falhadas
ACCOUNT_LOCKOUT_MAX_ATTEMPTS = 5
ACCOUNT_LOCKOUT_DURATION_SECONDS = 600  # 10 minutos

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('DJANGO_SECRET_KEY')
DEBUG = config('DEBUG', default=True, cast=bool)

# SECURITY WARNING: don't run with debug turned on in production!


ALLOWED_HOSTS = config("ALLOWED_HOSTS", cast=lambda v: [s.strip() for s in v.split(",")])
#ALLOWED_HOSTS = ['192.168.88.67','localhost','127.0.0.1','192.168.0.111','192.168.10.152']

# Application definition  s0VlTa6_@T}eT=CB
INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'api',
    

    #Para upload de imagens
    'cloudinary',
    'cloudinary_storage',

]
AUTH_USER_MODEL = 'api.User'

#DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # Paginação global — todos os endpoints de lista usam cursor pagination
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'api.exception_logging_middleware.ExceptionLoggingMiddleware',
    'api.request_logging_middleware.RequestLoggingMiddleware',
    'api.middleware.AuditMiddleware',
]
MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')

ROOT_URLCONF = 'iagromoz.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'iagromoz.wsgi.application'
SIMPLE_JWT = {
    # Access token: 15 min — token roubado expira rapidamente
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    # Refresh token: 7 dias — equilíbrio entre segurança e usabilidade
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


import dj_database_url

from decouple import config

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config("DATABASE_NAME"),
        "USER": config("DATABASE_USER"),
        "PASSWORD": config("DATABASE_PASSWORD"),
        "HOST": config("DATABASE_HOST"),
        "PORT": config("DATABASE_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-PT'

TIME_ZONE = 'Africa/Maputo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
STATIC_URL = '/static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (user-uploaded content)
# MEDIA_URL = '/media/'
# MEDIA_ROOT = BASE_DIR / 'media'
STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}


# ---------------------------------------------------------------------------
# CORS
# ---------------------------------------------------------------------------
# Em desenvolvimento (DEBUG=True): permite todas as origens por padrão
# Em produção (DEBUG=False): restringe às origens definidas em CORS_ALLOWED_ORIGINS
#
# Exemplos de configuração no .env:
#
#   Desenvolvimento:
#     CORS_ALLOW_ALL_ORIGINS=True
#
#   Produção:
#     CORS_ALLOW_ALL_ORIGINS=False
#     CORS_ALLOWED_ORIGINS=https://app.exemplo.com,https://www.app.exemplo.com

_cors_allow_all = config('CORS_ALLOW_ALL_ORIGINS', default=str(DEBUG), cast=bool)
_cors_origins_raw = config('CORS_ALLOWED_ORIGINS', default='')

CORS_ALLOW_ALL_ORIGINS = _cors_allow_all
CORS_ALLOWED_ORIGINS = [
    s.strip() for s in _cors_origins_raw.split(',') if s.strip()
] if not _cors_allow_all else []

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = list(default_headers) + ['authorization']

# ---------------------------------------------------------------------------
# Payments
# ---------------------------------------------------------------------------
# "MOCK"  → MockPaymentGateway (sem chamadas externas) — usar em dev/testes
# "LIVE"  → gateway real baseado no provider do Payment
PAYMENT_MODE = os.getenv('PAYMENT_MODE', 'MOCK')

# Forçar resultado do mock (opcional): "success" | "failed" | "processing"
# Se não definido, usa distribuição aleatória realista (80/15/5)
MOCK_PAYMENT_RESULT = os.getenv('MOCK_PAYMENT_RESULT', None)

# SEGURANÇA PARA PRODUÇÃO (Só ativa quando DEBUG=False)
if not DEBUG:
    # Redirecionar todo o tráfego HTTP para HTTPS
    SECURE_SSL_REDIRECT = True

    # Proteger os cookies para só passarem por HTTPS
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # HSTS - Força os navegadores a usarem sempre HTTPS
    SECURE_HSTS_SECONDS = 31536000  # 1 ano
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Previne que o browser adivinhe o content-type (MIME sniffing)
    SECURE_CONTENT_TYPE_NOSNIFF = True

    # Protecção XSS no browser
    SECURE_BROWSER_XSS_FILTER = True
    # Impede que a aplicação seja carregada num iframe (clickjacking)
    X_FRAME_OPTIONS = 'DENY'

# ---------------------------------------------------------------------------
# Logging — configuração completa em iagromoz/logging_config.py
# ---------------------------------------------------------------------------
from iagromoz.logging_config import LOGGING  # noqa: E402
